### ISSUE TITLE
Unable to search child item only using Control Type

### ISSUE THREAD

**Issue by codoid-repos** [leexgone/uiautomation-rs#11]
The below code is searching a pane under Notepad window, but it does not return the expected UI Element.

Note: If I add name or classname with control type, it works as expected. 

Expected: I should be able to find a child item only with Control Type.

`let automation: UIAutomation = UIAutomation::new().unwrap();
    let mut matcher = automation.create_matcher();

    let window = matcher.classname("Notepad").timeout(0).find_first().unwrap();

    let menuBar = automation.create_matcher()
         .from(window.clone())
         .control_type(UIA_PaneControlTypeId)
         .timeout(0)
         .find_first().unwrap();

     println!("{}", menuBar.get_framework_id().unwrap())`

**Comment by leexgone** [comment]
Fixed on v0.1.7

**Comment by codoid-repos** [comment]
@leexgone The fix is identifying elements, but it is not throwing an error when an element is not found.

**Comment by codoid-repos** [comment]
The below code should throw an error as it is searching a Window inside a Window.
`let window = matcher.classname("Notepad")
        .control_type(UIA_WindowControlTypeId)
        .timeout(0)
        .find_first()
        .unwrap();
    

    let menuBar = automation.create_matcher()
        .from(window.clone())
        .control_type(UIA_WindowControlTypeId)
        .timeout(0)
        .find_first().unwrap();`

**Comment by leexgone** [comment]
The `from(element) ` is not ignored when searching. So the root element is returned as the result.
I'll fixed it on the next version.
You can avoid it by setting more conditions now.

**Comment by leexgone** [comment]
Fixed on v0.1.8

**Comment by codoid-repos** [comment]
Thanks @leexgone. It works.
