### ISSUE TITLE
Element click is not clicking at center of the element

### ISSUE THREAD

**Issue by myasin-codoid** [leexgone/uiautomation-rs#21]
Element click is not clicking at center of the element. 

Issue: Element is getting clicked exactly at edge of the bounding rectangle. Due to this, click event is not triggered.

Expected: Element should be clicked at the center of the bounding rectangle.

**Comment by leexgone** [comment]
The element try to get the click point by `UIElement.get_clickable_point()` firstly.
When got failed, the element will try to calc the point by `UIElement.get_bounding_rectangle`.

You can print the results of  `UIElement.get_clickable_point()` and  `UIElement.get_bounding_rectangle` to debug before click.
FYI.
