### ISSUE TITLE
How to create a non-exe-process?

### ISSUE THREAD

**Issue by valeriigamaley** [leexgone/uiautomation-rs#40]
**_Introduction:_**

Hello again, guys. Now I have a common question: can I run a non-exe-process (such as .msi, or etc.)? Because `Process::create(path_to_exe)` works nice and start all exe installers, but if i tried that on .msi `Process::create(path_to_msi)` processes, it does not work. Can I use `Process` to start .msi installers?

**_Steps to reproduce:_**

1. Get some .msi installer
2. Try create process using a path to .msi

**_Software:_**
Win10 x64, rustc 1.69, cargo 1.69, uiautomation 0.51

**Comment by leexgone** [comment]
There is a `msiexec` command to invoke .msi files. You can pass the .msi file name as an argument to this command.
``` cmd
msiexec.exe /i "C:\example.msi" /qn
```
You may try this.

**Comment by valeriigamaley** [comment]
> 

that working idea, but msiexec need full path to run package installer. thx, i will think about how use non-full path to execute)
