### ISSUE TITLE
[Question] Caching support implementation ?

### ISSUE THREAD

**Issue by zbyna** [leexgone/uiautomation-rs#48]
Hello,
thanks for amazing library.
Does this project support [UIA caching](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomation-createcacherequest) ?

**Comment by leexgone** [comment]
It is not currently supported. 
I will look into it and support in future versions.
Thanks for your advice.

**Comment by zbyna** [comment]
Great! Thank you for response.

**Comment by leexgone** [comment]
This has been supported on `v0.9.0`.
