### ISSUE TITLE
[Question] Support for AddAutomationEventHandler 

### ISSUE THREAD

**Issue by elsnerpaul** [leexgone/uiautomation-rs#59]
Hi,
thanks to your library I can realize my current project in Rust instead falling back to C++ or C#.
Do you plan to support [AddAutomationEventHandler](https://learn.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomation-addautomationeventhandler) and similar functions in the future, too?
Right now I poll for UI changes but I hope I could avoid this with such event handlers.

Thanks!

**Comment by leexgone** [comment]
I will try to support this feature in future releases.But because the problem is somewhat complex, may need a period of time.

**Comment by elsnerpaul** [comment]
Would be awesome, thanks!

**Comment by leexgone** [comment]
Supported in v0.11.0.

Sample codes: <https://github.com/leexgone/uiautomation-rs/tree/main/samples/uia_event_handler>

**Comment by elsnerpaul** [comment]
Thanks!
