### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by elsnerpaul** [leexgone/uiautomation-rs#62]
Hi, I experience issues clicking on elements which are not on the primary screen.

I do `element.click()`, the cursor starts to move but stops at the edge of the primary monitor.

I'm going to build a small reproducer and debug the issue further soon, just wanted to let you know that there might be an issue and hear if you are aware of anything.

Paul

**Comment by leexgone** [comment]
This crate has not been tested in a multi-screen scenario yet, and I will also try to verify this issue.

**Comment by leexgone** [comment]
fixed on `v0.11.3`

**Comment by elsnerpaul** [comment]
Tested it and work now, thanks for the fix :)
