### ISSUE TITLE
Please allow access to cached child elements

### ISSUE THREAD

**Issue by steffen-goto** [leexgone/uiautomation-rs#63]
Please add access to GetCachedChildren() in uiautomation::core::UIElement

    pub fn get_cached_children(&self) -> Result<Vec<UIElement>> {
        let elements = unsafe { self.element.GetCachedChildren()? };
        Self::to_elements(elements)
    }

**Comment by leexgone** [comment]
Supported on v0.11.1

**Comment by steschu77** [comment]
Thanks for the quick fix!
