### ISSUE TITLE
[Ask] 对于Pane窗格控件怎么方便地将其置于前台

### ISSUE THREAD

**Issue by rust-kotlin** [leexgone/uiautomation-rs#75]
您好，我现在有个electron的程序必须置于前台才会去加载内部的DOM树内容，该程序的顶层控件是Pane不是Window，对于Window有个方法置于前台，对于Pane控件该怎么操作呢？

我尝试了set文本焦点，之前可以成功，但是在我今天Windows11自动更新之后不再可行，正在尝试其他办法。

```rust
  if expected_process_id == element.get_process_id().unwrap()
      && "QQ" != element.get_name().unwrap() // 寻找QQ的唯一子独立窗口
  {
      if let Err(e) = element.set_focus() {
          eprintln!("Failed to set focus: {:?}", e);
      }
      let pane: PaneControl = element.clone().try_into().unwrap();‘
.......
```

**Comment by rust-kotlin** [comment]
我用Accessibility Insights检查了一下，似乎Pane有的也是有Window operation的，比如SetWindowVisualState可以用来置于前台
<img width="413" alt="image" src="https://github.com/user-attachments/assets/f255288e-c54e-4a20-8a50-688f331198a7">
<img width="316" alt="image" src="https://github.com/user-attachments/assets/3c8469cf-4008-4786-b582-fb99b1c1b30d">

**Comment by rust-kotlin** [comment]
#76 我实现了一个函数，您可以看一下

**Comment by leexgone** [comment]
已经合并到`v0.12.1`版本上
